name: E2E tests

on:
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mrtnvh/circleci-node-lts-browsers-github-action:latest
    strategy:
      matrix:
        browsers: ['chrome', 'firefox']
    steps:
      # - run: who
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.4.1
      - name: Run
        run: npm run test:e2e
        env:
          TESTCAFE_BROWSER: ${{ matrix.browsers }}
